/** Demo 文案（UTF-8） */
export const ZH = {
  googleBanner: "结账优先：一行地址搜索，选中后自动带出国家 / 省州 / 城市与区号。",
  dr5hnBanner:
    "dr5hn 一行搜索国家 / 省州 / 城市（不含 CN），选中后自动带出区号，再填手机号、详细地址与邮编。",
  sectionRegion: "收货区域",
  sectionContact: "联系电话",
  sectionAddress: "详细地址",
  postal: "邮编",
  postalPlaceholder: "按当地格式填写（选填）",
  detailAddressPlaceholder: "街道、门牌号等",
  dr5hnSubmitHint: "选城市级结果并填完手机号与详细地址后，右侧 formReady 为 true。",
  dataSource: "数据源：",
  googleKeyHint: " 在 .env 配置 VITE_GOOGLE_MAPS_API_KEY 后切换为 Google Places。",
  providerGoogle: "Google Places",
  providerPhoton: "Photon（Demo 兜底）",
  providerGoogleFailed: "Photon（Google 加载失败）",
  addressSearchLabel: "地址搜索",
  addressSearchPlaceholder: "输入街道、门牌或地标…",
  regionSearchLabel: "国家 / 省市搜索",
  regionSearchPlaceholder: "输入城市、省州或国家名…",
  searching: "搜索中…",
  searchFailed: "搜索失败，请稍后重试。",
  regionSearchNoResults: "未找到匹配区域，请换关键词。",
  regionSearchChinaExcluded:
    "Beijing 等中国大陆城市已排除（CN）。请搜海外城市，例如 Dubai、London。",
  regionSearchCountryOnly: "已选国家；请继续输入城市名并选城市级结果。",
  regionSearchStateOnly: "已选省州；请继续输入城市名并选城市级结果。",
  regionSearchPhoneHint: "区号已自动带出：",
  regionSearchLevelCity: "城市",
  regionSearchLevelState: "省 / 州",
  regionSearchLevelCountry: "国家",
  country: "国家",
  state: "省 / 州",
  cityDistrict: "城市 / 区",
  empty: "—",
  phoneDial: "区号",
  phonePrefixEmpty: "—",
  phoneNumber: "手机号",
  phonePlaceholder: "仅填本地号码",
  detailAddress: "详细地址",
  detailAddress2: "补充地址（选填）",
  detailAddress2Placeholder: "楼层、单元等",
  bootWarn:
    "组件未加载：请在项目根目录执行 pnpm dev:unified-address（或各独立 Demo），不要用 IDE 直接打开 HTML。",
  unifiedProbing: "正在检测地址服务：dr5hn CDN → Photon → Google…",
  unifiedActiveProvider: "当前数据源：",
  unifiedProviderGoogle: "Google Places",
  unifiedProviderDr5hn: "dr5hn（国家/省/市，不含 CN）",
  unifiedProviderPhoton: "Photon（地址搜索兜底）",
  unifiedProbeFailed: "地址服务检测异常。",
  unifiedProbeFailedFallback: "已降级为 Photon。",
  unifiedRetry: "重新检测",
  unifiedBanner:
    "启动时自动选择：优先 dr5hn CDN，其次 Photon，再尝试 Google Key；均不可用则手填。检测期间显示骨架屏。",
} as const;
